server:
  port: 8082

spring:
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /subscriptions
      
#  autoconfigure:
#    exclude: 
#    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
#    - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
#    - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
      
logging:
  level:
    '[org.springframework.security]': DEBUG
    
    
